-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 18:35:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoUsuario` (
  `idtipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoUsuario`),
  UNIQUE INDEX `idtipoUsuario_UNIQUE` (`idtipoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `idDepartamentos` INT NOT NULL,
  `nombreDepartamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipios` (
  `idMunicipios` INT NOT NULL,
  `idDepartamentos` INT NOT NULL,
  PRIMARY KEY (`idMunicipios`),
  INDEX `fk_municipios_departamentos1_idx` (`idDepartamentos` ASC) VISIBLE,
  CONSTRAINT `fk_municipios_departamentos1`
    FOREIGN KEY (`idDepartamentos`)
    REFERENCES `mydb`.`departamentos` (`idDepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idtipoUsuario` INT NOT NULL,
  `idMunicipios` INT NOT NULL,
  `pNombre` VARCHAR(45) NOT NULL,
  `pApellido` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `numTelefono` VARCHAR(45) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `RTN` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_tipoUsuario1_idx` (`idtipoUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_municipios1_idx` (`idMunicipios` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_tipoUsuario1`
    FOREIGN KEY (`idtipoUsuario`)
    REFERENCES `mydb`.`tipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_municipios1`
    FOREIGN KEY (`idMunicipios`)
    REFERENCES `mydb`.`municipios` (`idMunicipios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calificacionesVendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calificacionesVendedor` (
  `idCalificacionVendedor` VARCHAR(45) NOT NULL,
  `cantidadEstrellas` INT NULL DEFAULT 0,1,2,3,5,
  `comentarios` VARCHAR(500) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCalificacionVendedor`),
  INDEX `fk_calificacionesVendedor_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_calificacionesVendedor_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calificacionesComprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calificacionesComprador` (
  `idcalificacionesComprador` INT NOT NULL,
  `cantidadEstrellas` INT NULL,
  `comentarios` VARCHAR(500) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idcalificacionesComprador`),
  INDEX `fk_calificacionesComprador_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_calificacionesComprador_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nombreCategoria` VARCHAR(80) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anuncios` (
  `idAnuncios` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idcategoria` INT NOT NULL,
  `idMunicipios` INT NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fechaPublicacion` DATE NOT NULL,
  `estadoArticulo` VARCHAR(20) NULL,
  `estadoAnuncio` VARCHAR(1) NOT NULL,
  `fechaLimite` DATE NULL,
  PRIMARY KEY (`idAnuncios`),
  INDEX `fk_anuncios_categoria1_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `fk_anuncios_municipios1_idx` (`idMunicipios` ASC) VISIBLE,
  INDEX `fk_anuncios_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_anuncios_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncios_municipios1`
    FOREIGN KEY (`idMunicipios`)
    REFERENCES `mydb`.`municipios` (`idMunicipios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncios_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`razonDenuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`razonDenuncia` (
  `idrazonDenuncia` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrazonDenuncia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Denuncias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Denuncias` (
  `idDenuncias` INT NOT NULL AUTO_INCREMENT,
  `idrazonDenuncia` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idDenuncias`),
  INDEX `fk_Denuncias_razonDenuncia1_idx` (`idrazonDenuncia` ASC) VISIBLE,
  INDEX `fk_Denuncias_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Denuncias_razonDenuncia1`
    FOREIGN KEY (`idrazonDenuncia`)
    REFERENCES `mydb`.`razonDenuncia` (`idrazonDenuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Denuncias_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
